package edu.gatech.cs6310;

public enum ErrorCode {
    STORE_ID_DUPLICATE, STORE_ID_NOT_FOUND, ITEM_ID_DUPLICATE, ITEM_ID_NOT_FOUND,
    PILOT_ID_DUPLICATE, PILOT_ID_NOT_FOUND, DRONE_ID_DUPLICATE, REFUELING_STATION_ID_DUPLICATE, DRONE_ID_NOT_FOUND,
    ORDER_ID_DUPLICATE, ORDER_ID_NOT_FOUND, DRONE_NEEDS_PILOT, DRONE_NEEDS_FUEL,
    CUSTOMER_ID_DUPLICATE, CUSTOMER_ID_NOT_FOUND, DRONE_INSUFFICIENT_CAPACITY, 
    NEW_DRONE_INSUFFICIENT_CAPACITY, ITEM_ALREADY_ORDERED, CUSTOMER_INSUFFICIENT_CREDIT, 
    DRONE_NO_CHANGE, PILOT_LICENSE_DUPLICATE, OK, UNKNOWN_ERROR,
    REFUELING_STATION_ID_NOT_FOUND, NOT_ENOUGH_FUEL, TRIP_UNROUTABLE, TIME_IN_PAST
}
